import os
import re
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from src.state import BrandContext

def generate_pdf(content: str, brand: BrandContext, output_path: str = "output.pdf") -> str:
    """
    Generates a brand-compliant PDF file, properly formatted with Platypus.
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        rightMargin=50,
        leftMargin=50,
        topMargin=50,
        bottomMargin=50
    )
    
    styles = getSampleStyleSheet()
    
    primary_color = brand.primary_color if hasattr(brand, 'primary_color') else "#7C3AED"
    
    title_style = ParagraphStyle(
        'BrandTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor(primary_color),
        spaceAfter=20
    )
    heading_style = ParagraphStyle(
        'BrandHeading',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor(primary_color),
        spaceBefore=15,
        spaceAfter=10
    )
    normal_style = ParagraphStyle(
        'BrandNormal',
        parent=styles['Normal'],
        fontSize=11,
        spaceBefore=5,
        spaceAfter=10,
        leading=16
    )
    
    # Process basic markdown mapping to exact reportlab HTML tags
    content = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', content)
    content = re.sub(r'_(.*?)_', r'<i>\1</i>', content)
    
    flowables = []
    
    flowables.append(Paragraph(brand.name, title_style))
    flowables.append(Spacer(1, 15))
    
    lines = content.split('\n')
    current_list = []
    
    for line in lines:
        line = line.strip()
        if not line:
            if current_list:
                flowables.append(ListFlowable(current_list, bulletType='bullet', spaceAfter=10))
                current_list = []
            continue
            
        if line.startswith('#'):
            if current_list:
                flowables.append(ListFlowable(current_list, bulletType='bullet', spaceAfter=10))
                current_list = []
                
            level = len(line) - len(line.lstrip('#'))
            text = line.lstrip('#').strip()
            
            if level == 1:
                flowables.append(Paragraph(text, title_style))
            else:
                flowables.append(Paragraph(text, heading_style))
                
        elif line.startswith(('- ', '* ')):
            text = line.lstrip('-* ').strip()
            item = ListItem(Paragraph(text, normal_style))
            current_list.append(item)
            
        else:
            if current_list:
                flowables.append(ListFlowable(current_list, bulletType='bullet', spaceAfter=10))
                current_list = []
            flowables.append(Paragraph(line, normal_style))
            
    if current_list:
        flowables.append(ListFlowable(current_list, bulletType='bullet', spaceAfter=10))

    def add_footer(canvas, doc):
        canvas.saveState()
        canvas.setFont('Helvetica-Oblique', 8)
        canvas.drawString(50, 30, f"Generated by AuraBrand - {brand.tone} Documentation")
        canvas.restoreState()

    doc.build(flowables, onFirstPage=add_footer, onLaterPages=add_footer)
    
    print(f"✅ PDF generated at: {output_path}")
    return os.path.abspath(output_path)
