import os
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from src.state import BrandContext

def generate_pdf(content: str, brand: BrandContext, output_path: str = "output.pdf") -> str:
    """
    Generates a brand-compliant PDF file.
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    c = canvas.Canvas(output_path, pagesize=letter)
    width, height = letter

    # 1. Branding Header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 50, brand.name)
    
    # Simple line separator
    c.setStrokeColorRGB(0.5, 0.2, 1.0) # Brand Purpleish
    c.line(50, height - 60, width - 50, height - 60)

    # 2. Content
    c.setFont("Helvetica", 11)
    text_object = c.beginText(50, height - 100)
    text_object.setLeading(14)
    
    # Basic wrapping/new lines
    for line in content.split("\n"):
        # Very simple wrapping by splitting lines
        # In a production app, we would use Platypus for complex wrapping
        text_object.textLine(line)
        
    c.drawText(text_object)

    # 3. Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(50, 30, f"Generated by AuraBrand - {brand.tone} Documentation")

    c.showPage()
    c.save()
    
    print(f"✅ PDF generated at: {output_path}")
    return os.path.abspath(output_path)
